resolver: lts-5.17

packages:
- '.'
- location:
    git:    'https://github.com/andrewthad/haskell-ip'
    commit: '3ccce5ddb6a9d60ca13dc50545b678da1f17c8e0'
  extra-dep: true

# extra-deps:
# - 'ip-0.6.0'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

